import React, { useState } from "react";
import { Link } from "react-router-dom";
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import "react-bootstrap-table-next/dist/react-bootstrap-table2.min.css";
import "react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.min.css";
import ToolkitProvider, {
  Search,
  CSVExport,
} from "react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit";
import Button from "react-bootstrap/Button";
import Modal from "react-bootstrap/Modal";
import filterFactory, { dateFilter, Comparator } from "react-bootstrap-table2-filter";

const ViewContracts = () => {
  // Data for table
  const data = [
    {
      id: "1",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      id: "2",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      id: "3",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      id: "4",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      id: "5",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      id: "6",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      id: "7",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      id: "8",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      id: "9",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      id: "10",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      id: "11",
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    /*{
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },*/
  ];

  // Adding s_no to data
  const doubled = data.map((item, idx) => (item.s_no = idx + 1));

  // Link to edit table data
  const linkFollow = (cell, row, rowIndex, formatExtraData) => {
    return <Link to="/edit">{row.packageName}</Link>;
  };

  //For delete modal
  const [showModal, setModalShow] = useState(false);
  const handleClose = () => {
    setRowToDelete({});
    setModalShow(false);
  };
  const handleShow = () => setModalShow(true);

  //Data to be deleted
  const [rowToDelete, setRowToDelete] = useState({});

  // Columns for table
  const columns = [
    {
      dataField: "s_no",
      text: "S/No.",
      headerStyle: { minWidth: "50px", backgroundColor: "#A7C7E7" },
      style: { width: "fit-content" },
      sort: false,
    },
    {
      dataField: "packageName",
      text: "Package Name",
      headerAlign: "center",
      headerStyle: { minWidth: "250px", backgroundColor: "#A7C7E7" },
      //formatter: linkFollow,
      sort: true,
    },
    {
      dataField: "dateAwarded",
      text: "Awarded Date",
      headerAlign: "center",
      formatter: dateFormatter,
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
      filter: dateFilter({
        withoutEmptyComparatorOption: true,
        comparators: [Comparator.EQ, Comparator.GT, Comparator.LT],
        style: { display: "inline" },
        className: "custom-datefilter-class",
        comparatorStyle: { backgroundColor: "#9ebfd6" },
        comparatorClassName: "custom-comparator-class",
        dateStyle: { backgroundColor: "#9ebfd6", margin: "0px" },
        dateClassName: "custom-date-class",
      }),
    },
    {
      dataField: "valueWithGST",
      text: "Value",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "procurementNature",
      text: "Procurement Nature",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "throughGeM",
      text: "Through GeM",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
      searchable: false,
    },
    {
      dataField: "gemMode",
      text: "GeM Mode",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "notGeMReason",
      text: "Reason",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "itemOnGeM",
      text: "Available on GeM",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
      searchable: false,
    },
    {
      dataField: "notGeMApprovingOfficer",
      text: "Approver",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "availabilityReport",
      text: "Availability Report",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
      searchable: false,
    },
    {
      dataField: "action",
      text: "Action",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      align: "center",
      formatter: (cellContent, row) => {
        return (
          <>
            <button
              className="btn btn-danger btn-xs deleteContract"
              onClick={() => {
                setModalShow(true);
                setRowToDelete(row);
              }}
            >
              <i className="fa fa-trash" aria-hidden="true"></i>
            </button>
          </>
        );
      },
    },
  ];

  // Delete function
  const handleDelete = (row) => {
    console.log(row);
    // Todo - delete API call

    setRowToDelete({});
    setModalShow(false);
  };

  // Date formatter
  const moment = require("moment");
  function dateFormatter(cell) {
    return <span>{moment(cell).format("DD-MM-YYYY")}</span>;
  }

  // Default sort on table
  const defaultSorted = [
    {
      dataField: "dateAwarded",
      order: "desc",
    },
  ];

  const customTotal = (from, to, size) => (
    <span className="react-bootstrap-table-pagination-total">
      Showing {from} to {to} of {size} Results
    </span>
  );

  const options = {
    paginationSize: 5,
    pageStartIndex: 1,
    // alwaysShowAllBtns: true, // Always show next and previous button
    // withFirstAndLast: false, // Hide the going to First and Last page button
    // hideSizePerPage: true, // Hide the sizePerPage dropdown always
    hidePageListOnlyOnePage: true, // Hide the pagination list when only one page
    firstPageText: "First",
    prePageText: "Back",
    nextPageText: "Next",
    lastPageText: "Last",
    nextPageTitle: "First page",
    prePageTitle: "Pre page",
    firstPageTitle: "Next page",
    lastPageTitle: "Last page",
    showTotal: true,
    paginationTotalRenderer: customTotal,
    disablePageTitle: true,
    //buttonsAlwaysShown: ["Back","Next","Last","First"],
    sizePerPageList: [
      {
        text: "10",
        value: 10,
      },
      {
        text: "20",
        value: 20,
      },
      {
        text: "All",
        value: data.length,
      },
    ],
  };

  const { SearchBar } = Search;
  const { ExportCSVButton } = CSVExport;

  return (
    <>
      <div className="content-wrapper">
        <section className="content-header">
          <div className="container-fluid">
            <div className="row mb-2">
              <div className="col-sm-6">
                <h1>View Contracts</h1>
              </div>
              <div className="col-sm-6">
                <ol className="breadcrumb float-sm-right">
                  <li className="breadcrumb-item">
                    <Link to="/">Home</Link>
                  </li>
                  <li className="breadcrumb-item active">View Contracts</li>
                </ol>
              </div>
            </div>
          </div>
        </section>

        <section className="content">
          <div className="container-fluid">
            <div className="row">
              <div className="col-12">
                <div className="card">
                  <div className="card-header">
                    <h3 className="card-title"></h3>
                  </div>

                  <div className="card">
                    <div className="card-header">
                      <h3 className="card-title"></h3>
                    </div>

                    <div className="card-body">
                      <ToolkitProvider
                        keyField="id"
                        data={data}
                        columns={columns}
                        search
                        exportCSV
                      >
                        {(props) => (
                          <div
                            id="example1_wrapper"
                            className="dataTables_wrapper dt-bootstrap4"
                          >
                            <div className="row">
                              <div className="col-sm-12 col-md-6">
                                <ExportCSVButton
                                  {...props.csvProps}
                                  className="btn btn-secondary buttons-csv buttons-html5"
                                  tabIndex="0"
                                  aria-controls="example1"
                                  type="button"
                                >
                                  <i className="fas fa-solid fa-file-csv fa-2x"></i>
                                </ExportCSVButton>
                              </div>
                              <div className="col-sm-12 col-md-6">
                                <div
                                  id="example1_filter"
                                  className="dataTables_filter"
                                >
                                  <SearchBar
                                    {...props.searchProps}
                                    type="search"
                                    className="form-control form-control-sm"
                                    placeholder=""
                                    aria-controls="example1"
                                  ></SearchBar>
                                </div>
                              </div>
                            </div>
                            <hr />
                            <BootstrapTable
                              {...props.baseProps}
                              bootstrap4
                              wrapperClasses="table-responsive"
                              data={data}
                              columns={columns}
                              pagination={paginationFactory(options)}
                              striped
                              hover
                              condensed
                              defaultSorted={defaultSorted}
                              keyField="id"
                              filter={filterFactory()}
                            />
                          </div>
                        )}
                      </ToolkitProvider>
                      <Modal
                        show={showModal}
                        onHide={handleClose}
                        backdrop="static"
                        centered
                        keyboard="False"
                        size="sm"
                      >
                        <Modal.Body>Do you want to delete?</Modal.Body>
                        <Modal.Footer justifyContent="space-between">
                          <Button variant="secondary" onClick={handleClose}>
                            No
                          </Button>
                          <Button
                            variant="danger"
                            onClick={() => {
                              handleDelete(rowToDelete);
                            }}
                            align="right"
                          >
                            Yes...Delete It!
                          </Button>
                        </Modal.Footer>
                      </Modal>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default ViewContracts;
