import React from "react";
import { Link } from "react-router-dom";
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from "react-bootstrap-table2-paginator";
import "react-bootstrap-table-next/dist/react-bootstrap-table2.min.css";
import "react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.min.css";
import ToolkitProvider, {
  Search,
  CSVExport,
} from "react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit";

const ViewContracts = () => {
  // Data for table
  const data = [
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "Yes",
      gemMode: "bidding",
      notGeMReason: "NA",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "NA",
      availabilityReport: "NA",
    },
    {
      packageName: "Desktop Procurement",
      dateAwarded: "2022-12-23T18:25:43.511Z",
      valueWithGST: "100000",
      procurementNature: "Civil",
      throughGeM: "No",
      gemMode: "NA",
      notGeMReason: "Urgent",
      itemOnGeM: "Yes",
      notGeMApprovingOfficer: "ankit",
      availabilityReport: "Yes",
    },
  ];

  // Link to edit table data
  {
    /* const linkFollow = (cell, row, rowIndex, formatExtraData) => {
    return <Link to="/edit">{row.Engine}</Link>;
  };*/
  }

  // Columns for table
  const columns = [
    {
      dataField: "s_no",
      text: "S/No.",
      formatter: (cell, row, rowIndex, formatExtraData) => {
        return rowIndex + 1;
      },
      headerStyle: { minWidth: "50px", backgroundColor: "#A7C7E7" },
      style: { width: "fit-content" },
    },
    {
      dataField: "packageName",
      text: "Package Name",
      headerAlign: "center",
      headerStyle: { minWidth: "250px", backgroundColor: "#A7C7E7" },
      //formatter: linkFollow,
      sort: true,
      //headerStyle: (colum, colIndex) => {
      //  return { width: "100px", textAlign: "center" };
      //},
    },
    {
      dataField: "dateAwarded",
      text: "Awarded Date",
      headerAlign: "center",
      formatter: dateFormatter,
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "valueWithGST",
      text: "Value",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "procurementNature",
      text: "Procurement Nature",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "throughGeM",
      text: "Through GeM",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
      searchable: false,
    },
    {
      dataField: "gemMode",
      text: "GeM Mode",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "notGeMReason",
      text: "Reason",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "itemOnGeM",
      text: "Available on GeM",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
      searchable: false,
    },
    {
      dataField: "notGeMApprovingOfficer",
      text: "Approver",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
    },
    {
      dataField: "availabilityReport",
      text: "Availability Report",
      headerAlign: "center",
      headerStyle: { minWidth: "100px", backgroundColor: "#A7C7E7" },
      sort: true,
      searchable: false,
    },
  ];

  // Date formatter
  const moment = require("moment");
  function dateFormatter(cell) {
    return <span>{moment(cell).format("DD-MM-YYYY")}</span>;
  }

  // Default sort on table
  const defaultSorted = [
    {
      dataField: "dateAwarded",
      order: "desc",
    },
  ];

  const customTotal = (from, to, size) => (
    <span className="react-bootstrap-table-pagination-total">
      Showing {from} to {to} of {size} Results
    </span>
  );

  const options = {
    paginationSize: 5,
    pageStartIndex: 1,
    // alwaysShowAllBtns: true, // Always show next and previous button
    // withFirstAndLast: false, // Hide the going to First and Last page button
    // hideSizePerPage: true, // Hide the sizePerPage dropdown always
    hidePageListOnlyOnePage: true, // Hide the pagination list when only one page
    firstPageText: "First",
    prePageText: "Back",
    nextPageText: "Next",
    lastPageText: "Last",
    nextPageTitle: "First page",
    prePageTitle: "Pre page",
    firstPageTitle: "Next page",
    lastPageTitle: "Last page",
    showTotal: true,
    paginationTotalRenderer: customTotal,
    disablePageTitle: true,
    //buttonsAlwaysShown: ["Back","Next","Last","First"],
    sizePerPageList: [
      {
        text: "10",
        value: 10,
      },
      {
        text: "20",
        value: 20,
      },
      {
        text: "All",
        value: data.length,
      },
    ],
  };

  const { SearchBar } = Search;
  const { ExportCSVButton } = CSVExport;

  return (
    <>
      <div className="content-wrapper">
        <section className="content-header">
          <div className="container-fluid">
            <div className="row mb-2">
              <div className="col-sm-6">
                <h1>View Contracts</h1>
              </div>
              <div className="col-sm-6">
                <ol className="breadcrumb float-sm-right">
                  <li className="breadcrumb-item">
                    <Link to="/">Home</Link>
                  </li>
                  <li className="breadcrumb-item active">View Contracts</li>
                </ol>
              </div>
            </div>
          </div>
        </section>

        <section className="content">
          <div className="container-fluid">
            <div className="row">
              <div className="col-12">
                <div className="card">
                  <div className="card-header">
                    <h3 className="card-title"></h3>
                  </div>

                  <div className="card">
                    <div className="card-header">
                      <h3 className="card-title"></h3>
                    </div>

                    <div className="card-body">
                      <ToolkitProvider
                        keyField="id"
                        data={data}
                        columns={columns}
                        search
                        exportCSV
                      >
                        {(props) => (
                          <div
                            id="example1_wrapper"
                            className="dataTables_wrapper dt-bootstrap4"
                          >
                            <div className="row">
                              <div className="col-sm-12 col-md-6">
                                {/*<div className="dt-buttons btn-group flex-wrap">
                                  {" "}
                                  <button
                                    className="btn btn-secondary buttons-copy buttons-html5"
                                    tabIndex="0"
                                    aria-controls="example1"
                                    type="button"
                                  >
                                    <span>Copy</span>
                                  </button>{" "}
                                  
                                  <button
                                    className="btn btn-secondary buttons-excel buttons-html5"
                                    tabIndex="0"
                                    aria-controls="example1"
                                    type="button"
                                  >
                                    <span>Excel</span>
                                  </button>{" "}
                                  <button
                                    className="btn btn-secondary buttons-pdf buttons-html5"
                                    tabIndex="0"
                                    aria-controls="example1"
                                    type="button"
                                  >
                                    <span>PDF</span>
                                  </button>{" "}
                                  <button
                                    className="btn btn-secondary buttons-print"
                                    tabIndex="0"
                                    aria-controls="example1"
                                    type="button"
                                  >
                                    <span>Print</span>
                                  </button>{" "}
                                  <div className="btn-group">
                                    <button
                                      className="btn btn-secondary buttons-collection dropdown-toggle buttons-colvis"
                                      tabIndex="0"
                                      aria-controls="example1"
                                      type="button"
                                      aria-haspopup="true"
                                    >
                                      <span>Column visibility</span>
                                      <span className="dt-down-arrow"></span>
                                    </button>
                                  </div>{" "}
                                </div>*/}
                                <ExportCSVButton
                                  {...props.csvProps}
                                  className="btn btn-secondary buttons-csv buttons-html5"
                                  tabIndex="0"
                                  aria-controls="example1"
                                  type="button"
                                >
                                  <i className="fas fa-solid fa-file-csv fa-2x"></i>
                                </ExportCSVButton>
                              </div>
                              <div className="col-sm-12 col-md-6">
                                <div
                                  id="example1_filter"
                                  className="dataTables_filter"
                                >
                                  <SearchBar
                                    {...props.searchProps}
                                    type="search"
                                    className="form-control form-control-sm"
                                    placeholder=""
                                    aria-controls="example1"
                                  >
                                  </SearchBar>
                                </div>
                              </div>
                            </div>
                            <hr />
                            <BootstrapTable
                              {...props.baseProps}
                              bootstrap4
                              wrapperClasses="table-responsive"
                              keyField="id"
                              data={data}
                              columns={columns}
                              pagination={paginationFactory(options)}
                              striped
                              hover
                              condensed
                              defaultSorted={defaultSorted}
                            />
                          </div>
                        )}
                      </ToolkitProvider>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default ViewContracts;
